mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.github.shikra.server.mapper
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.129.23:13306/oauth_data?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: wangwangdui
    password: 0HYQ2PxYdn!Pyl^E
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 # 初始化时建立物理连接的个数
      min-idle: 5  # 最小连接池数量
      max-active: 20 # 最大连接池数量 maxIdle已经不再使用
      max-wait: 60000 # 获取连接时最大等待时间，单位毫秒
      test-while-idle: true  # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      time-between-eviction-runs-millis: 60000 # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      min-evictable-idle-time-millis: 60000  # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      validation-query: select 'x' # 用来检测连接是否有效的sql 必须是一个查询语句
      test-on-borrow: false # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false  # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      pool-prepared-statements: true # 是否缓存preparedStatement,mysql5.5+建议开启
      max-pool-prepared-statement-per-connection-size: 20  # 当值大于0时poolPreparedStatements会自动修改为true
      filters: stat,wall,slf4j  # 配置扩展插件
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true  # 合并多个DruidDataSource的监控数据
      stat-view-servlet: # 设置访问druid监控页的账号和密码,默认没有
        login-username: admin
        login-password: admin123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
management:
  endpoint:
    health:
      show-details: always